zookeeper error on zoo_create, path /rtb-test/serviceClass/rtbRequestRouter/router: node exists

--------------------------[Exception thrown]---------------------------
time:   2014-04-22-074157
type:   ML::Exception
pid:    8492; tid: 8492
what:   Zookeeper error on zoo_create, path /rtb-test/serviceClass/rtbRequestRouter/router: node exists
stack:
00: 0x0x7f56fea70db7 at __cxa_throw + 0x27 in /home/rtbkit/rtbkit/build/x86_64/bin/../bin/libexception_hook.so + 0xdb7/home/rtbkit/rtbkit/build/x86_64/bin/../bin/libexception_hook.so(__cxa_throw+0x27) [0x7f56fea70db7]
01: 0x0x7f56fcb717c3 at Datacratic::ZookeeperConnection::checkRes(int, int&, char const*, char const*) + 0xe3 in /home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so + 0x1097c3/home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so(_ZN10Datacratic19ZookeeperConnection8checkResEiRiPKcS3_+0xe3) [0x7f56fcb717c3]
02: 0x0x7f56fcb713c1 at Datacratic::ZookeeperConnection::createNode(std::string const&, std::string const&, bool, bool, bool, bool) + 0x441 in /home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so + 0x1093c1/home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so(_ZN10Datacratic19ZookeeperConnection10createNodeERKSsS2_bbbb+0x441) [0x7f56fcb713c1]
03: 0x0x7f56fcb2a695 at Datacratic::ZookeeperConfigurationService::setUnique(std::string const&, Json::Value const&) + 0x285 in /home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so + 0xc2695/home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so(_ZN10Datacratic29ZookeeperConfigurationService9setUniqueERKSsRKN4Json5ValueE+0x285) [0x7f56fcb2a695]
04: 0x0x7f56fcb16004 at Datacratic::ServiceBase::registerServiceProvider(std::string const&, std::vector<std::string, std::allocator<std::string> > const&) + 0x1c4 in /home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so + 0xae004/home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so(_ZN10Datacratic11ServiceBase23registerServiceProviderERKSsRKSt6vectorISsSaISsEE+0x1c4) [0x7f56fcb16004]
05: 0x0x7f56fe3747d4 at RTBKIT::Router::init() + 0xd4 in /home/rtbkit/rtbkit/build/x86_64/bin/../bin/librtb_router.so + 0x7a7d4/home/rtbkit/rtbkit/build/x86_64/bin/../bin/librtb_router.so(_ZN6RTBKIT6Router4initEv+0xd4) [0x7f56fe3747d4]
06: 0x0x421e74 at RTBKIT::RouterRunner::init() + 0x304 in build/x86_64/bin/router_runner + 0x21e74build/x86_64/bin/router_runner(_ZN6RTBKIT12RouterRunner4initEv+0x304) [0x421e74]
07: 0x0x4201ae at main + 0x6e in build/x86_64/bin/router_runner + 0x201aebuild/x86_64/bin/router_runner(main+0x6e) [0x4201ae]
08: 0x0x7f56fd4d776d at __libc_start_main + 0xed in /lib/x86_64-linux-gnu/libc.so.6 + 0x2176d/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xed) [0x7f56fd4d776d]
09: 0x0x4208a9 in build/x86_64/bin/router_runner + 0x208a9build/x86_64/bin/router_runner() [0x4208a9]

terminate called after throwing an instance of 'ML::Exception'
  what():  Zookeeper error on zoo_create, path /rtb-test/serviceClass/rtbRequestRouter/router: node exists
